<template><div class="space-y-4"><div class="cyber-card rounded-xl p-6"><h2 class="text-xl font-bold mb-4" style="color:#00f0ff">⚡ 性能监控</h2><div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div v-for="m in metrics" :key="m.label" class="rounded-lg p-4" style="background:#0d0d1a;border:1px solid #00f0ff30"><div class="text-xs" style="color:#a0a0cc">{{m.label}}</div><div class="text-2xl font-bold mt-1" :style="{color:m.color}">{{m.value}}</div><div class="w-full h-1 rounded mt-2" style="background:#1a1a2e"><div class="h-full rounded" :style="{width:m.pct+'%',background:m.color}"></div></div></div></div></div><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div class="cyber-card rounded-xl p-6"><h3 class="text-sm font-bold mb-3" style="color:#00f0ff">磁盘I/O</h3><div class="space-y-2"><div v-for="d in disks" :key="d.m" class="flex justify-between text-sm"><span style="color:#e0e0ff">{{d.m}}</span><span style="color:#00f0ff">{{d.u}}/{{d.t}}</span></div></div></div><div class="cyber-card rounded-xl p-6"><h3 class="text-sm font-bold mb-3" style="color:#00f0ff">网络流量</h3><div class="flex items-end gap-1 h-24"><div v-for="(v,i) in net" :key="i" class="flex-1 rounded-t" :style="{height:v+'%',background:i%2?'#00f0ff':'#00f0ff',minWidth:'3px'}"></div></div><div class="flex justify-between text-xs mt-2"><span style="color:#00f0ff">↑ 2.3MB/s</span><span style="color:#00f0ff">↓ 8.1MB/s</span></div></div></div></div></template>
<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue'
const metrics=ref([{label:'CPU',value:'37%',color:'#00f0ff',pct:37},{label:'内存',value:'4.2/8GB',color:'#00f0ff',pct:52},{label:'磁盘',value:'28/100GB',color:'#b700ff',pct:28},{label:'带宽',value:'45Mbps',color:'#ffe600',pct:45}])
const disks=ref([{m:'/',u:'28GB',t:'100GB'},{m:'/data',u:'156GB',t:'500GB'}])
const net=ref(Array(30).fill(0).map(()=>Math.floor(Math.random()*80+10)))
let t:any
onMounted(()=>{t=setInterval(()=>{metrics.value.forEach(m=>{m.pct=Math.floor(Math.random()*60+10);m.value=m.pct+'%'});net.value.shift();net.value.push(Math.floor(Math.random()*80+10))},2000)})
onUnmounted(()=>clearInterval(t))
</script>