<template><div class="space-y-4"><div class="cyber-card rounded-xl p-6"><h2 class="text-xl font-bold mb-4" style="color:#00f0ff">🔴 实时监控</h2><div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div v-for="m in metrics" :key="m.label" class="rounded-lg p-4" style="background:#0d0d1a;border:1px solid #00f0ff30"><div class="text-xs" style="color:#a0a0cc">{{m.label}}</div><div class="text-2xl font-bold mt-1" :style="{color:m.color}">{{m.value}}</div></div></div></div><div class="cyber-card rounded-xl p-6"><h3 class="text-sm font-bold mb-3" style="color:#00f0ff">实时请求量</h3><div class="flex items-end gap-1 h-32"><div v-for="(v,i) in chart" :key="i" class="flex-1 rounded-t" :style="{height:v+'%',background:'linear-gradient(180deg,#00f0ff,#b700ff)',minWidth:'3px'}"></div></div></div><div class="cyber-card rounded-xl p-6"><h3 class="text-sm font-bold mb-3" style="color:#00f0ff">实时事件流</h3><div class="space-y-1 max-h-48 overflow-y-auto"><div v-for="e in events" :key="e.id" class="flex gap-3 text-xs p-2 rounded" style="background:#0d0d1a"><span :style="{color:e.color}">{{e.time}}</span><span style="color:#e0e0ff">{{e.msg}}</span></div></div></div></div></template>
<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue'
const metrics=ref([{label:'在线用户',value:'128',color:'#00f0ff'},{label:'QPS',value:'342',color:'#00f0ff'},{label:'CPU',value:'37%',color:'#b700ff'},{label:'内存',value:'62%',color:'#ffe600'}])
const chart=ref(Array(60).fill(20))
const events=ref<any[]>([])
let timer:any
onMounted(()=>{timer=setInterval(()=>{metrics.value[0].value=String(Math.floor(Math.random()*200+50));metrics.value[1].value=String(Math.floor(Math.random()*500+100));metrics.value[2].value=Math.floor(Math.random()*40+20)+'%';metrics.value[3].value=Math.floor(Math.random()*30+40)+'%';chart.value.shift();chart.value.push(Math.floor(Math.random()*80+10));const ts=new Date().toTimeString().slice(0,8);const msgs=['用户登录','AI请求','订单创建','文件上传','API调用','注册审核','支付成功','Token消耗'];const colors=['#00f0ff','#00f0ff','#b700ff','#ffe600','#00ff88','#ff6b35'];const idx=Math.floor(Math.random()*msgs.length);events.value.unshift({id:Date.now(),time:ts,msg:msgs[idx]+' #'+Math.floor(Math.random()*9999),color:colors[idx]});if(events.value.length>30)events.value.pop()},1000)})
onUnmounted(()=>clearInterval(timer))
</script>